# Copyright (C) 2002-2025 Free Software Foundation, Inc.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <https://www.gnu.org/licenses/>.
#
# As a special exception to the GNU General Public License,
# this file may be distributed as part of a program that
# contains a configuration script generated by Autoconf, under
# the same distribution terms as the rest of that program.
#
# Generated by gnulib-tool.
#
# This file represents the specification of how gnulib-tool is used.
# It acts as a cache: It is written and read by gnulib-tool.
# In projects that use version control, this file is meant to be put under
# version control, like the configure.ac and various Makefile.am files.


# Specification in the form of a command-line invocation:
# gnulib-tool --import \
#  --local-dir=gl \
#  --lib=libcoreutils \
#  --source-base=lib \
#  --m4-base=m4 \
#  --doc-base=doc \
#  --tests-base=gnulib-tests \
#  --aux-dir=build-aux \
#  --with-tests \
#  --makefile-name=gnulib.mk \
#  --automake-subdir \
#  --no-conditional-dependencies \
#  --no-libtool \
#  --macro-prefix=gl \
#  --avoid=canonicalize-lgpl \
#  --avoid=dummy \
#  --avoid=mbuiter \
#  --avoid=mbuiterf \
#  acl \
#  acl-permissions \
#  alignalloc \
#  alignasof \
#  alloca \
#  announce-gen \
#  areadlink-with-size \
#  areadlinkat-with-size \
#  argmatch \
#  argv-iter \
#  assert \
#  assert-h \
#  assure \
#  attribute \
#  autobuild \
#  backup-rename \
#  backupfile \
#  base32 \
#  base64 \
#  bool \
#  btoc32 \
#  buffer-lcm \
#  c-strcase \
#  c32iscntrl \
#  c32isspace \
#  c32width \
#  canon-host \
#  canonicalize \
#  chmodat \
#  chown \
#  chownat \
#  cl-strtod \
#  cl-strtold \
#  closein \
#  closeout \
#  config-h \
#  configmake \
#  copy-file-range \
#  crc-x86_64 \
#  crypto/md5 \
#  crypto/sha1 \
#  crypto/sha256 \
#  crypto/sha512 \
#  crypto/sm3 \
#  cycle-check \
#  d-ino \
#  d-type \
#  di-set \
#  dirfd \
#  dirname \
#  do-release-commit-and-tag \
#  dtoastr \
#  dup2 \
#  endian \
#  environ \
#  error \
#  euidaccess \
#  exclude \
#  exitfail \
#  explicit_bzero \
#  faccessat \
#  fadvise \
#  fchdir \
#  fchmodat \
#  fchownat \
#  fclose \
#  fcntl \
#  fcntl-safer \
#  fd-reopen \
#  fdatasync \
#  fdopen \
#  fdutimensat \
#  file-has-acl \
#  file-type \
#  fileblocks \
#  filemode \
#  filenamecat \
#  filevercmp \
#  flexmember \
#  fnmatch-gnu \
#  fopen-safer \
#  fprintftime \
#  fpurge \
#  free-posix \
#  freopen \
#  freopen-safer \
#  fseeko \
#  fstatat \
#  fsusage \
#  fsync \
#  ftoastr \
#  ftruncate \
#  fts \
#  full-read \
#  full-write \
#  gethrxtime \
#  getline \
#  getloadavg \
#  getlogin \
#  getndelim2 \
#  getopt-gnu \
#  getpagesize \
#  gettext-h \
#  gettime \
#  gettime-res \
#  git-version-gen \
#  gitlog-to-changelog \
#  gnu-web-doc-update \
#  gnumakefile \
#  gnupload \
#  hard-locale \
#  hash \
#  hash-triple \
#  heap \
#  host-os \
#  human \
#  idcache \
#  idx \
#  ignore-value \
#  inttostr \
#  inttypes-h \
#  isapipe \
#  isatty \
#  isblank \
#  largefile \
#  lchmod \
#  ldtoastr \
#  lib-ignore \
#  libgmp \
#  linebuffer \
#  link \
#  link-follow \
#  linkat \
#  long-options \
#  lstat \
#  maintainer-makefile \
#  malloc-gnu \
#  manywarnings \
#  mbrlen \
#  mbrtoc32 \
#  mbrtowc \
#  mbschr \
#  mbslen \
#  mbswidth \
#  mbszero \
#  mcel-prefer \
#  memcasecmp \
#  memchr \
#  memcmp2 \
#  mempcpy \
#  memrchr \
#  minmax \
#  mkancesdirs \
#  mkdir \
#  mkdir-p \
#  mkdirat \
#  mkfifo \
#  mkfifoat \
#  mknod \
#  mkostemp \
#  mkstemp \
#  mktime \
#  modechange \
#  mountlist \
#  mpsort \
#  nproc \
#  nstrftime \
#  nullptr \
#  obstack \
#  open \
#  openat-safer \
#  parse-datetime \
#  parse-datetime2 \
#  pathmax \
#  perl \
#  physmem \
#  pipe-posix \
#  pipe2 \
#  posix-shell \
#  posixtm \
#  posixver \
#  priv-set \
#  progname \
#  propername-lite \
#  pthread-cond \
#  pthread-mutex \
#  pthread-thread \
#  pthread_sigmask \
#  putenv-gnu \
#  quote \
#  quotearg \
#  randint \
#  randperm \
#  rawmemchr \
#  read-file \
#  readtokens \
#  readtokens0 \
#  readutmp \
#  regex \
#  remove \
#  renameat \
#  renameatu \
#  rmdir \
#  root-dev-ino \
#  safe-read \
#  same \
#  save-cwd \
#  savedir \
#  savewd \
#  select \
#  selinux-at \
#  setenv \
#  settime \
#  sig2str \
#  sigaction \
#  skipchars \
#  smack \
#  ssize_t \
#  stat-macros \
#  stat-size \
#  stat-time \
#  stdc_leading_zeros \
#  stdc_trailing_zeros \
#  stdckdint-h \
#  stdlib-safer \
#  stpcpy \
#  strdup-posix \
#  strnlen \
#  strnumcmp \
#  strsignal \
#  strtoimax \
#  strtoumax \
#  symlinkat \
#  sys_ioctl-h \
#  sys_resource-h \
#  sys_stat-h \
#  sys_types-h \
#  sys_wait-h \
#  targetdir \
#  tempname \
#  termios-h \
#  time_rz \
#  timer-time \
#  timespec \
#  tmpdir \
#  uname \
#  unicodeio \
#  unistd-safer \
#  unlink-busy \
#  unlinkat \
#  unlinkdir \
#  unlocked-io \
#  unsetenv \
#  update-copyright \
#  useless-if-before-free \
#  userspec \
#  utimecmp \
#  utimens \
#  utimensat \
#  vasprintf-posix \
#  vc-list-files \
#  verify \
#  verror \
#  version-etc-fsf \
#  winsz-ioctl \
#  winsz-termios \
#  write-any-file \
#  xalignalloc \
#  xalloc \
#  xbinary-io \
#  xdectoint \
#  xfts \
#  xgetcwd \
#  xgetgroups \
#  xgethostname \
#  xmemcoll \
#  xnanosleep \
#  xprintf \
#  xprintf-posix \
#  xreadlink \
#  xstrtod \
#  xstrtoimax \
#  xstrtol \
#  xstrtol-error \
#  xstrtold \
#  xstrtoumax \
#  xvasprintf \
#  year2038-recommended \
#  yesno

# Specification in the form of a few gnulib-tool.m4 macro invocations:
gl_LOCAL_DIR([gl])
gl_MODULES([
  acl
  acl-permissions
  alignalloc
  alignasof
  alloca
  announce-gen
  areadlink-with-size
  areadlinkat-with-size
  argmatch
  argv-iter
  assert
  assert-h
  assure
  attribute
  autobuild
  backup-rename
  backupfile
  base32
  base64
  bool
  btoc32
  buffer-lcm
  c-strcase
  c32iscntrl
  c32isspace
  c32width
  canon-host
  canonicalize
  chmodat
  chown
  chownat
  cl-strtod
  cl-strtold
  closein
  closeout
  config-h
  configmake
  copy-file-range
  crc-x86_64
  crypto/md5
  crypto/sha1
  crypto/sha256
  crypto/sha512
  crypto/sm3
  cycle-check
  d-ino
  d-type
  di-set
  dirfd
  dirname
  do-release-commit-and-tag
  dtoastr
  dup2
  endian
  environ
  error
  euidaccess
  exclude
  exitfail
  explicit_bzero
  faccessat
  fadvise
  fchdir
  fchmodat
  fchownat
  fclose
  fcntl
  fcntl-safer
  fd-reopen
  fdatasync
  fdopen
  fdutimensat
  file-has-acl
  file-type
  fileblocks
  filemode
  filenamecat
  filevercmp
  flexmember
  fnmatch-gnu
  fopen-safer
  fprintftime
  fpurge
  free-posix
  freopen
  freopen-safer
  fseeko
  fstatat
  fsusage
  fsync
  ftoastr
  ftruncate
  fts
  full-read
  full-write
  gethrxtime
  getline
  getloadavg
  getlogin
  getndelim2
  getopt-gnu
  getpagesize
  gettext-h
  gettime
  gettime-res
  git-version-gen
  gitlog-to-changelog
  gnu-web-doc-update
  gnumakefile
  gnupload
  hard-locale
  hash
  hash-triple
  heap
  host-os
  human
  idcache
  idx
  ignore-value
  inttostr
  inttypes-h
  isapipe
  isatty
  isblank
  largefile
  lchmod
  ldtoastr
  lib-ignore
  libgmp
  linebuffer
  link
  link-follow
  linkat
  long-options
  lstat
  maintainer-makefile
  malloc-gnu
  manywarnings
  mbrlen
  mbrtoc32
  mbrtowc
  mbschr
  mbslen
  mbswidth
  mbszero
  mcel-prefer
  memcasecmp
  memchr
  memcmp2
  mempcpy
  memrchr
  minmax
  mkancesdirs
  mkdir
  mkdir-p
  mkdirat
  mkfifo
  mkfifoat
  mknod
  mkostemp
  mkstemp
  mktime
  modechange
  mountlist
  mpsort
  nproc
  nstrftime
  nullptr
  obstack
  open
  openat-safer
  parse-datetime
  parse-datetime2
  pathmax
  perl
  physmem
  pipe-posix
  pipe2
  posix-shell
  posixtm
  posixver
  priv-set
  progname
  propername-lite
  pthread-cond
  pthread-mutex
  pthread-thread
  pthread_sigmask
  putenv-gnu
  quote
  quotearg
  randint
  randperm
  rawmemchr
  read-file
  readtokens
  readtokens0
  readutmp
  regex
  remove
  renameat
  renameatu
  rmdir
  root-dev-ino
  safe-read
  same
  save-cwd
  savedir
  savewd
  select
  selinux-at
  setenv
  settime
  sig2str
  sigaction
  skipchars
  smack
  ssize_t
  stat-macros
  stat-size
  stat-time
  stdc_leading_zeros
  stdc_trailing_zeros
  stdckdint-h
  stdlib-safer
  stpcpy
  strdup-posix
  strnlen
  strnumcmp
  strsignal
  strtoimax
  strtoumax
  symlinkat
  sys_ioctl-h
  sys_resource-h
  sys_stat-h
  sys_types-h
  sys_wait-h
  targetdir
  tempname
  termios-h
  time_rz
  timer-time
  timespec
  tmpdir
  uname
  unicodeio
  unistd-safer
  unlink-busy
  unlinkat
  unlinkdir
  unlocked-io
  unsetenv
  update-copyright
  useless-if-before-free
  userspec
  utimecmp
  utimens
  utimensat
  vasprintf-posix
  vc-list-files
  verify
  verror
  version-etc-fsf
  winsz-ioctl
  winsz-termios
  write-any-file
  xalignalloc
  xalloc
  xbinary-io
  xdectoint
  xfts
  xgetcwd
  xgetgroups
  xgethostname
  xmemcoll
  xnanosleep
  xprintf
  xprintf-posix
  xreadlink
  xstrtod
  xstrtoimax
  xstrtol
  xstrtol-error
  xstrtold
  xstrtoumax
  xvasprintf
  year2038-recommended
  yesno
])
gl_AVOID([canonicalize-lgpl dummy mbuiter mbuiterf])
gl_SOURCE_BASE([lib])
gl_M4_BASE([m4])
gl_PO_BASE([])
gl_DOC_BASE([doc])
gl_TESTS_BASE([gnulib-tests])
gl_WITH_TESTS
gl_LIB([libcoreutils])
gl_MAKEFILE_NAME([gnulib.mk])
gl_AUTOMAKE_SUBDIR
gl_MACRO_PREFIX([gl])
gl_PO_DOMAIN([])
gl_WITNESS_C_MACRO([])
